In [1]:
import pandas as pd

In [2]:
dfs = []
for i in range(0, 4):
    df = pd.read_excel("Data.xlsx", sheet_name=i)
    df.columns = df.columns.str.strip()
    # Loại bỏ khoảng trắng ở đầu và cuối của dữ liệu
    df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
    df = df.map(lambda x: x.title() if isinstance(x, str) else x)
    dfs.append(df)

# Kiểm tra các giá trị null(hoặc nan) trong từng bảng

In [3]:
for df in dfs:
    print(df.isna().sum())

ID nhân viên                      0
Loại                              0
Nơi cư trú                        1
Kinh nghiệm làm việc tại Viện     0
Kinh nghiệm trong ngành           1
Sàn nhà                           0
Tuổi                              3
Có sẵn công việc bán thời gian    0
dtype: int64
ID nhân viên        0
Hạng mục nhân sự    0
Danh mục câu hỏi    0
Mã câu hỏi 1        0
Câu hỏi             0
Trả lời             0
dtype: int64
ID nhân viên                              0
Hạng mục nhân sự                          0
Hạng mục câu hỏi                          0
Mã câu hỏi 2                              0
Câu hỏi                                   0
Đánh giá tầm quan trọng của các yếu tố    0
Đánh giá mức độ hài lòng                  0
dtype: int64
ID nhân viên                              0
Hạng mục nhân sự                          0
Hạng mục câu hỏi                          0
Mã câu hỏi 3                              0
Câu hỏi                                   0
Đánh giá tầm quan trọng của các yếu tố    0
Đánh giá mức độ hài lòng                  0
dtype: int64

Bảng "Nhân viên" xuất hiện các giá trị nan, chúng ta sẽ xử lí các giá trị này

In [4]:
# lấy ra bảng đầu tiên ("Nhân viên")
df = dfs[0]

In [5]:
# tổng quan về bảng dữ liệu
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID nhân viên                    165 non-null    int64
 1   Loại                            165 non-null    object
 2   Nơi cư trú                      164 non-null    object
 3   Kinh nghiệm làm việc tại Viện   165 non-null    int64
 4   Kinh nghiệm trong ngành         164 non-null    float64
 5   Sàn nhà                         165 non-null    int64
 6   Tuổi                            162 non-null    float64
 7   Có sẵn công việc bán thời gian  165 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 10.4+ KB

,ID nhân viên,Loại,Nơi cư trú,Kinh nghiệm làm việc tại Viện,Kinh nghiệm trong ngành,Sàn nhà,Tuổi,Có sẵn công việc bán thời gian
0,1,Sự Quản Lý,Mátxcơva,6,32.0,1,55.0,1
1,2,Nhân Viên Y Tế,Kosterevo,4,4.0,0,40.0,0
2,3,Bác Sĩ,Mátxcơva,1,3.0,1,25.0,0
3,4,Nhân Viên Y Tế,Mátxcơva,6,NaN,0,47.0,0
4,5,Bác Sĩ,Mátxcơva,40,40.0,1,71.0,0
...,...,...,...,...,...,...,...,...
160,161,Bác Sĩ,Mátxcơva,37,40.0,1,62.0,0
161,162,Bác Sĩ,Mátxcơva,6,20.0,0,45.0,1
162,163,Nhân Viên Y Tế,Mátxcơva,20,20.0,0,39.0,1
163,164,Bác Sĩ,Mátxcơva,17,17.0,0,41.0,0
164,165,Bác Sĩ,Mátxcơva,22,30.0,1,52.0,0

# Xử lí dữ liệu

In [7]:
# Các giá trị nan trong cột "Kinh nghiệm trong ngành", chúng ta sẽ để giá trị = -1, sau đó ép kiểu dữ liệu cho cột này thành int
df["Kinh nghiệm trong ngành"] = df["Kinh nghiệm trong ngành"].fillna(-1).astype(int)
df

,ID nhân viên,Loại,Nơi cư trú,Kinh nghiệm làm việc tại Viện,Kinh nghiệm trong ngành,Sàn nhà,Tuổi,Có sẵn công việc bán thời gian
0,1,Sự Quản Lý,Mátxcơva,6,32,1,55.0,1
1,2,Nhân Viên Y Tế,Kosterevo,4,4,0,40.0,0
2,3,Bác Sĩ,Mátxcơva,1,3,1,25.0,0
3,4,Nhân Viên Y Tế,Mátxcơva,6,-1,0,47.0,0
4,5,Bác Sĩ,Mátxcơva,40,40,1,71.0,0
...,...,...,...,...,...,...,...,...
160,161,Bác Sĩ,Mátxcơva,37,40,1,62.0,0
161,162,Bác Sĩ,Mátxcơva,6,20,0,45.0,1
162,163,Nhân Viên Y Tế,Mátxcơva,20,20,0,39.0,1
163,164,Bác Sĩ,Mátxcơva,17,17,0,41.0,0
164,165,Bác Sĩ,Mátxcơva,22,30,1,52.0,0

## Xem xét một chút 2 cột "Kinh nghiệm làm việc" và "Kinh nghiệm trong ngành": ta thấy rằng số năm kinh nghiệm trong ngành luôn phải lớn hơn hoặc bằng số năm kinh nghiệm làm việc!

In [8]:
# tìm ra các bản ghi có dữ liệu không phù hợp với điều kiện đã đưa ra
mask = (df["Kinh nghiệm trong ngành"] < df["Kinh nghiệm làm việc tại Viện"])

In [9]:
# Các bản ghi không phù hợp
df[mask]

,ID nhân viên,Loại,Nơi cư trú,Kinh nghiệm làm việc tại Viện,Kinh nghiệm trong ngành,Sàn nhà,Tuổi,Có sẵn công việc bán thời gian
3,4,Nhân Viên Y Tế,Mátxcơva,6,-1,0,47.0,0
13,14,Nhân Viên Phục Vụ,Mátxcơva,7,4,1,32.0,0
106,107,Bác Sĩ,Mátxcơva,20,18,1,40.0,1
107,108,Bác Sĩ,Mátxcơva,30,28,1,56.0,1
138,139,Nhân Viên Y Tế,Mátxcơva,3,2,0,26.0,0
139,140,Nhân Viên Y Tế,Mátxcơva,33,30,0,57.0,0

In [10]:
# Sửa lỗi (nếu có): Gán giá trị hợp lý cho "Kinh nghiệm làm việc trong ngành"
df.loc[mask, "Kinh nghiệm trong ngành"] = df.loc[mask,"Kinh nghiệm làm việc tại Viện"]

In [12]:
df

,ID nhân viên,Loại,Nơi cư trú,Kinh nghiệm làm việc tại Viện,Kinh nghiệm trong ngành,Sàn nhà,Tuổi,Có sẵn công việc bán thời gian
0,1,Sự Quản Lý,Mátxcơva,6,32,1,55.0,1
1,2,Nhân Viên Y Tế,Kosterevo,4,4,0,40.0,0
2,3,Bác Sĩ,Mátxcơva,1,3,1,25.0,0
3,4,Nhân Viên Y Tế,Mátxcơva,6,6,0,47.0,0
4,5,Bác Sĩ,Mátxcơva,40,40,1,71.0,0
...,...,...,...,...,...,...,...,...
160,161,Bác Sĩ,Mátxcơva,37,40,1,62.0,0
161,162,Bác Sĩ,Mátxcơva,6,20,0,45.0,1
162,163,Nhân Viên Y Tế,Mátxcơva,20,20,0,39.0,1
163,164,Bác Sĩ,Mátxcơva,17,17,0,41.0,0
164,165,Bác Sĩ,Mátxcơva,22,30,1,52.0,0

In [13]:
# kiểm tra lại, ta thấy không còn bản ghi nào không phù hợp với điều kiện đã đưa ra
df[df["Kinh nghiệm trong ngành"] < df["Kinh nghiệm làm việc tại Viện"]]

Empty DataFrame
Columns: [ID nhân viên, Loại, Nơi cư trú, Kinh nghiệm làm việc tại Viện, Kinh nghiệm trong ngành, Sàn nhà, Tuổi, Có sẵn công việc bán thời gian]
Index: []

## Tương tự như cột "Kinh nghiệm làm việc", ta cũng sẽ thay thế các giá trị nan trong cột "Tuổi" = -1 và ép kiểu dữ liệu trong cột này thành "int"

In [14]:
df['Tuổi']=df["Tuổi"].fillna(-1).astype(int)

## Đặt Vấn đề với cột "Tuổi":
### Đầu tiên, ta sẽ tạo một cột mới có tên là "Tuổi bắt đầu làm việc" để tính toán độ tuổi mà một nhân viên bắt đầu làm việc(hành nghề) bằng cách lấy số Tuổi - Kinh nghiệm trong ngành.
### Dựa trên cột "Nơi cư trú", ta sẽ giả định các nhân viên này đều làm việc tại Nga. Theo đó, theo luật lao động ở Nga, các chức vụ trong cột "Loại" sẽ có số tuổi được quy định để bắt đầu công việc:
####   'Nhân Viên Phục Vụ': 18 -> đủ 18 tuổi mới được nhận công việc này
####   'Nhân Viên Y Tế': 18 -> đủ 18 tuổi hơn
####   'Bác Sĩ': 22 -> đủ 22 tuổi hoặc hơn
####   'Sự Quản Lý': 25 -> đủ 25 hoặc hơn

## So sánh các giá trị trong cột "Tuổi bắt đầu làm việc" với các giá trị được quy định trên, ta sẽ thấy có những bản ghi không phù hợp, kéo theo các giá trị trong cột "Tuổi" của các bản ghi này cũng sẽ có vấn đề (cột "Kinh nghiệm trong ngành" đã được chỉnh sửa trước)

In [15]:
min_age_by_position = {
    'Nhân Viên Phục Vụ': 18,
    'Nhân Viên Y Tế': 18,
    'Bác Sĩ': 22,
    'Sự Quản Lý': 25
}

# Áp dụng tuổi tối thiểu vào một cột mới
df['Tuổi tối thiểu hợp lý'] = df['Loại'].map(min_age_by_position)

# Kiểm tra các dòng có vi phạm (tuổi hiện tại - số kinh nghiệm trong ngành < tuổi tối thiểu hợp lý)
mask_age_violation = (df['Tuổi'] -df["Kinh nghiệm trong ngành"]) < df['Tuổi tối thiểu hợp lý']
mask_age_violation = mask_age_violation.reindex(df.index)


print("Các dòng có dữ liệu không hợp lệ:")
print(df[mask_age_violation][df["Loại"] =="Bác Sĩ"])
print(df[mask_age_violation][df["Loại"] =="Nhân Viên Y Tế"])
print(df[mask_age_violation][df["Loại"] =="Nhân Viên Phục Vụ"])
print(df[mask_age_violation][df["Loại"] =="Sự Quản Lý"])

Các dòng có dữ liệu không hợp lệ:
     ID nhân viên    Loại  Nơi cư trú  Kinh nghiệm làm việc tại Viện  \
5               6  Bác Sĩ          Mo                              4
57             58  Bác Sĩ    Mátxcơva                              1
84             85  Bác Sĩ    Mátxcơva                              4
87             88  Bác Sĩ    Mátxcơva                              9
106           107  Bác Sĩ    Mátxcơva                             20
109           110  Bác Sĩ    Mátxcơva                             15
119           120  Bác Sĩ   Mytishchi                              6
123           124  Bác Sĩ  Ramenskoye                             11
125           126  Bác Sĩ         NaN                             20
126           127  Bác Sĩ    Mátxcơva                              2
143           144  Bác Sĩ    Mátxcơva                             45
155           156  Bác Sĩ  Shchelkovo                              4

     Kinh nghiệm trong ngành  Sàn nhà  Tuổi  Có sẵn công việc bán thời gian  \
5                          9        1    -1                               1
57                        26        0    47                               0
84                         8        1    27                               1
87                        40        1    60                               1
106                       20        1    40                               1
109                       35        0    55                               0
119                        8        1    -1                               0
123                       18        1    32                               1
125                       25        1    45                               1
126                        5        1    26                               1
143                       53        1    70                               0
155                       24        0    43                               1

     Tuổi tối thiểu hợp lý
5                       22
57                      22
84                      22
87                      22
106                     22
109                     22
119                     22
123                     22
125                     22
126                     22
143                     22
155                     22
    ID nhân viên            Loại Nơi cư trú  Kinh nghiệm làm việc tại Viện  \
73            74  Nhân Viên Y Tế   Mátxcơva                              1

    Kinh nghiệm trong ngành  Sàn nhà  Tuổi  Có sẵn công việc bán thời gian  \
73                        1        1    18                               0

    Tuổi tối thiểu hợp lý
73                     18
Empty DataFrame
Columns: [ID nhân viên, Loại, Nơi cư trú, Kinh nghiệm làm việc tại Viện, Kinh nghiệm trong ngành, Sàn nhà, Tuổi, Có sẵn công việc bán thời gian, Tuổi tối thiểu hợp lý]
Index: []
     ID nhân viên        Loại Nơi cư trú  Kinh nghiệm làm việc tại Viện  \
0               1  Sự Quản Lý   Mátxcơva                              6
26             27  Sự Quản Lý   Pushkino                              4
46             47  Sự Quản Lý   Mátxcơva                             19
56             57  Sự Quản Lý   Mátxcơva                              2
61             62  Sự Quản Lý   Mátxcơva                             40
62             63  Sự Quản Lý   Mátxcơva                             19
65             66  Sự Quản Lý   Mátxcơva                             31
70             71  Sự Quản Lý   Mátxcơva                             54
71             72  Sự Quản Lý   Mátxcơva                             13
83             84  Sự Quản Lý     Reutov                             32
110           111  Sự Quản Lý   Mátxcơva                              1
137           138  Sự Quản Lý   Mátxcơva                             32

     Kinh nghiệm trong ngành  Sàn nhà  Tuổi  Có sẵn công việc bán thời gian  \
0                         32        1    55                               1
26                        49        1    73                               0
46                        27        0    44                               0
56                         2        0    24                               0
61                        40        0    -1                               0
62                        29        0    52                               0
65                        33        0    54                               0
70                        54        0    71                               0
71                        20        0    39                               0
83                        32        0    52                               0
110                       26        1    46                               0
137                       32        0    54                               0

     Tuổi tối thiểu hợp lý
0                       25
26                      25
46                      25
56                      25
61                      25
62                      25
65                      25
70                      25
71                      25
83                      25
110                     25
137                     25

C:\Users\ACER\AppData\Local\Temp\ipykernel_14284\2082500469.py:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[mask_age_violation][df["Loại"] =="Bác Sĩ"])
C:\Users\ACER\AppData\Local\Temp\ipykernel_14284\2082500469.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[mask_age_violation][df["Loại"] =="Nhân Viên Y Tế"])
C:\Users\ACER\AppData\Local\Temp\ipykernel_14284\2082500469.py:19: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[mask_age_violation][df["Loại"] =="Nhân Viên Phục Vụ"])
C:\Users\ACER\AppData\Local\Temp\ipykernel_14284\2082500469.py:20: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[mask_age_violation][df["Loại"] =="Sự Quản Lý"])

In [16]:
# cập nhật lại dữ liệu trong cột "Tuổi"
df.loc[mask_age_violation, "Tuổi"] = df.loc[mask_age_violation, "Tuổi tối thiểu hợp lý"] + df.loc[mask_age_violation, "Kinh nghiệm trong ngành"]

In [17]:
# kiểm tra lại các giá trị trong cột "Tuổi", "Tuổi tối thiểu hợp lý" và "Kinh nghiệm trong ngành"
df

,ID nhân viên,Loại,Nơi cư trú,Kinh nghiệm làm việc tại Viện,Kinh nghiệm trong ngành,Sàn nhà,Tuổi,Có sẵn công việc bán thời gian,Tuổi tối thiểu hợp lý
0,1,Sự Quản Lý,Mátxcơva,6,32,1,57,1,25
1,2,Nhân Viên Y Tế,Kosterevo,4,4,0,40,0,18
2,3,Bác Sĩ,Mátxcơva,1,3,1,25,0,22
3,4,Nhân Viên Y Tế,Mátxcơva,6,6,0,47,0,18
4,5,Bác Sĩ,Mátxcơva,40,40,1,71,0,22
...,...,...,...,...,...,...,...,...,...
160,161,Bác Sĩ,Mátxcơva,37,40,1,62,0,22
161,162,Bác Sĩ,Mátxcơva,6,20,0,45,1,22
162,163,Nhân Viên Y Tế,Mátxcơva,20,20,0,39,1,18
163,164,Bác Sĩ,Mátxcơva,17,17,0,41,0,22
164,165,Bác Sĩ,Mátxcơva,22,30,1,52,0,22

## Thay thế giá trị nan trong cột "Nơi cư trú": vì trong cột này chỉ xuất hiện 1 giá trị nan nên chúng ta sẽ sử dụng mode() để thay thế giá trị nan

In [18]:
x = df["Nơi cư trú"].mode()[0]
x
df["Nơi cư trú"].fillna(x, inplace = True)
df["Nơi cư trú"].isna().sum()

C:\Users\ACER\AppData\Local\Temp\ipykernel_14284\685711316.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Nơi cư trú"].fillna(x, inplace = True)

np.int64(0)

In [19]:
for sheet in range(len(dfs)):
    # Đặt tên file xuất ra, ví dụ: 'sheet_name.xlsx'
    output_file = f'{sheet}.xlsx'
    
    # Xuất DataFrame ra file Excel
    dfs[sheet].to_excel(output_file, index=False)
    print(f'Exported {sheet} to {output_file}')

Exported 0 to 0.xlsx
Exported 1 to 1.xlsx
Exported 2 to 2.xlsx
Exported 3 to 3.xlsx